Repository dharmaprotocol/charta, pull requests merged in 2018-05, with the labels that each got.

#116 Remove requirement that token symbol list length not exceed 256 in TokenRegistry
  contracts/TokenRegistry.sol
Labels: needs-review

#120 Test suite for the contract registry contract
  contracts/ContractRegistry.sol
  contracts/test/mocks/MockDebtRegistry.sol
  test/ts/logs/contract_registry.ts
  test/ts/logs/log_utils.ts
  test/ts/unit/contract_registry.ts
  types/common.ts
Labels: needs-review, test

#121 Changes to #119 stemming from code review
  test/ts/migrations/2_deploy_dharma_contracts_test.ts
  test/ts/unit/collateralized_simple_interest_terms_contract.ts
  test/ts/unit/simple_interest_terms_contract.ts
Labels: needs-review

#119 Fix existing test suites given the introduction of the contract registry
  contracts/ContractRegistry.sol
  contracts/examples/CollateralizedSimpleInterestTermsContract.sol
  contracts/examples/SimpleInterestTermsContract.sol
  contracts/test/mocks/MockDebtRegistry.sol
  migrations/2_deploy_dharma_contracts.js
  migrations/3_deploy_test_contracts.js
  migrations/4_deploy_terms_contracts.js
  migrations/migration_constants.js
  migrations/utils.js
  test/ts/logs/contract_registry.ts
  test/ts/logs/log_utils.ts
  test/ts/migrations/2_deploy_dharma_contracts_test.ts
  test/ts/migrations/3_deploy_test_contracts_test.ts
  test/ts/migrations/4_deploy_terms_contracts_test.ts
  test/ts/migrations/6_transfer_ownership_to_multisig.ts
  test/ts/unit/collateralized_simple_interest_terms_contract.ts
  test/ts/unit/contract_registry.ts
  test/ts/unit/simple_interest_terms_contract.ts
  types/common.ts
Labels: reviewed

#118 Introduce contract registry
  contracts/ContractRegistry.sol
  contracts/examples/CollateralizedSimpleInterestTermsContract.sol
  contracts/examples/SimpleInterestTermsContract.sol
  contracts/test/mocks/MockDebtRegistry.sol
  migrations/2_deploy_dharma_contracts.js
  migrations/3_deploy_test_contracts.js
  migrations/4_deploy_terms_contracts.js
  migrations/6_transfer_ownership_to_multisig.js
  migrations/migration_constants.js
  migrations/utils.js
  test/ts/logs/contract_registry.ts
  test/ts/logs/log_utils.ts
  test/ts/migrations/2_deploy_dharma_contracts_test.ts
  test/ts/migrations/3_deploy_test_contracts_test.ts
  test/ts/migrations/4_deploy_terms_contracts_test.ts
  test/ts/migrations/6_transfer_ownership_to_multisig.ts
  test/ts/unit/collateralized_simple_interest_terms_contract.ts
  test/ts/unit/contract_registry.ts
  test/ts/unit/simple_interest_terms_contract.ts
  types/common.ts
Labels: needs-review

#123 Update test suites to reflect api changes to the permissions library
  contracts/test/DummyContract.sol
  test/ts/logs/debt_registry.ts
  test/ts/logs/log_utils.ts
  test/ts/logs/permissions_lib.ts
  test/ts/test_utils/multisig.ts
  test/ts/unit/collateralizer/collateralizer.ts
  test/ts/unit/contract_registry.ts
  test/ts/unit/debt_registry.ts
  test/ts/unit/debt_token.ts
  test/ts/unit/permissions.ts
  test/ts/unit/token_transfer_proxy.ts
  types/common.ts
Labels: needs-review, test

#117 Specify events in PermissionsLib
  contracts/Collateralizer.sol
  contracts/DebtRegistry.sol
  contracts/DebtToken.sol
  contracts/TokenTransferProxy.sol
  contracts/libraries/PermissionsLib.sol
  contracts/test/DummyContract.sol
  test/ts/logs/debt_registry.ts
  test/ts/logs/log_utils.ts
  test/ts/logs/permissions_lib.ts
  test/ts/test_utils/multisig.ts
  test/ts/unit/collateralizer/collateralizer.ts
  test/ts/unit/contract_registry.ts
  test/ts/unit/debt_registry.ts
  test/ts/unit/debt_token.ts
  test/ts/unit/permissions.ts
  test/ts/unit/token_transfer_proxy.ts
  types/common.ts
Labels: needs-review

#124 Make the Debt Token Integration Test Suite Great Again (MtDTITSGA)
  test/ts/integration/debt_token.ts
  test/ts/test_utils/multisig.ts
Labels: needs-review, test

#126 build: use deployed canonical WETH address on Kovan
  migrations/migration_constants.js
  migrations/utils.js
Labels: needs-review

#127 Add the DAI stablecoin to the token registry
  migrations/migration_constants.js
Labels: needs-review
