Repository dharmaprotocol/charta, pull requests merged in 2018-04, with the labels that each got.

#71 Add collateralizer runner files
  test/ts/factories/terms_contract_parameters.ts
  test/ts/unit/collateralizer/collateralizer.ts
  test/ts/unit/collateralizer/runners/collateralize.ts
  test/ts/unit/collateralizer/runners/index.ts
  test/ts/unit/collateralizer/runners/return_collateral.ts
  test/ts/unit/collateralizer/runners/seize_collateral.ts
Labels: Split Collateralizer

#70 Add mock test contract files and migrations for collateralizer
  contracts/Collateralizer.sol
  contracts/test/mocks/MockCollateralizedTermsContract.sol
  contracts/test/mocks/MockTermsContract.sol
  migrations/3_deploy_test_contracts.js
  test/ts/factories/terms_contract_parameters.ts
  test/ts/unit/collateralizer/collateralizer.ts
  test/ts/unit/collateralizer/runners/collateralize.ts
  test/ts/unit/collateralizer/runners/index.ts
  test/ts/unit/collateralizer/runners/return_collateral.ts
  test/ts/unit/collateralizer/runners/seize_collateral.ts
Labels: Split Collateralizer

#69 Remove collateralized_contract.ts and add test scenarios for collateralizer
  contracts/Collateralizer.sol
  contracts/test/mocks/MockCollateralizedTermsContract.sol
  contracts/test/mocks/MockTermsContract.sol
  migrations/3_deploy_test_contracts.js
  test/ts/factories/terms_contract_parameters.ts
  test/ts/unit/collateralizer/collateralizer.ts
  test/ts/unit/collateralizer/runners/collateralize.ts
  test/ts/unit/collateralizer/runners/index.ts
  test/ts/unit/collateralizer/runners/return_collateral.ts
  test/ts/unit/collateralizer/runners/seize_collateral.ts
  test/ts/unit/collateralizer/scenarios/successful_collateralization.ts
  test/ts/unit/collateralizer/scenarios/successful_return.ts
  test/ts/unit/collateralizer/scenarios/successful_seizure.ts
  test/ts/unit/collateralizer/scenarios/unsuccessful_collateralization.ts
  test/ts/unit/collateralizer/scenarios/unsuccessful_return.ts
  test/ts/unit/collateralizer/scenarios/unsuccessful_seizure.ts
Labels: Split Collateralizer

#78 Add collateralized simple interest terms contract tests
  contracts/Collateralizer.sol
  migrations/2_deploy_dharma_contracts.js
  migrations/3_deploy_test_contracts.js
  migrations/4_deploy_terms_contracts.js
  migrations/5_authorize_contract_interactions.js
  test/ts/factories/terms_contract_parameters.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/collateralized_simple_interest_terms_contract.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/runners/collateralized_simple_interest_terms_contract.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/runners/index.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/runners/register_repayment.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/runners/register_term_start.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/runners/unpack_parameters_from_bytes.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/scenarios/index.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/scenarios/successful_register_repayment.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/scenarios/successful_register_term_start.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/scenarios/unpack_parameters_from_bytes.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/scenarios/unsuccessful_register_repayment.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/scenarios/unsuccessful_register_term_start.ts
  test/ts/unit/collateralizer/collateralizer.ts
  test/ts/unit/collateralizer/runners/return_collateral.ts
  test/ts/unit/collateralizer/runners/seize_collateral.ts
  test/ts/unit/debt_registry.ts
Labels: test

#76 Test suite for `safeTransferFrom`
  contracts/test/mocks/MockERC721Receiver.sol
  migrations/3_deploy_test_contracts.js
  test/ts/test_utils/send_transactions.ts
  test/ts/unit/debt_token.ts
Labels: test

#90 test: add multisig tests
  migrations/2_deploy_dharma_contracts.js
  migrations/6_transfer_ownership_to_multisig.js
  migrations/migration_constants.js
  test/ts/integration/debt_kernel.ts
  test/ts/integration/repayment_router.ts
  test/ts/logs/debt_kernel.ts
  test/ts/logs/debt_token.ts
  test/ts/logs/multisig_wallet.ts
  test/ts/migrations/2_deploy_dharma_contracts_test.ts
  test/ts/migrations/3_deploy_test_contracts_test.ts
  test/ts/test_utils/utils.ts
  test/ts/unit/token_transfer_proxy.ts
  types/common.ts
Labels: reviewed

#85 Interest rate calculations must account for orders of magnitude in percentages
  contracts/examples/SimpleInterestTermsContract.sol
  test/ts/factories/terms_contract_parameters.ts
  test/ts/integration/debt_kernel.ts
  test/ts/integration/debt_token.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/runners/collateralized_simple_interest_terms_contract.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/runners/register_term_start.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/runners/unpack_parameters_from_bytes.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/scenarios/index.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/scenarios/successful_register_term_start.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/scenarios/unpack_parameters_from_bytes.ts
  test/ts/integration/examples/simple_interest_terms_contract/runners/register_term_start.ts
  test/ts/integration/examples/simple_interest_terms_contract/runners/simple_interest_terms_contract.ts
  test/ts/integration/examples/simple_interest_terms_contract/scenarios/index.ts
  test/ts/integration/examples/simple_interest_terms_contract/scenarios/successful_register_term_start.ts
  test/ts/integration/examples/simple_interest_terms_contract/scenarios/unpack_parameters_from_bytes.ts
  test/ts/integration/repayment_router.ts
  test/ts/test_utils/units.ts
  test/ts/unit/collateralized_simple_interest_terms_contract.ts
  test/ts/unit/debt_kernel.ts
  test/ts/unit/debt_registry.ts
  test/ts/unit/debt_token.ts
  test/ts/unit/simple_interest_terms_contract.ts
Labels: needs-review

#94 test: add tests for deploying terms contracts
  test/ts/migrations/4_deploy_terms_contracts_test.ts
Labels: needs-review

#102 Add token names to registry
  contracts/TokenRegistry.sol
  migrations/2_deploy_dharma_contracts.js
  migrations/3_deploy_test_contracts.js
  migrations/migration_constants.js
  test/ts/integration/repayment_router.ts
  test/ts/integration/token_registry.ts
  test/ts/migrations/3_deploy_test_contracts_test.ts
  test/ts/test_utils/utils.ts
Labels: needs-review

#109 test: Add basic test suite for `DharmaMultiSigWallet`
  contracts/test/mocks/MockDebtToken.sol
  contracts/wallet/DharmaMultiSigWallet.sol
  contracts/wallet/MultiSigWallet.sol
  test/ts/integration/debt_kernel.ts
  test/ts/integration/dharma_multisig_wallet.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/collateralized_simple_interest_terms_contract.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/runners/collateralized_simple_interest_terms_contract.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/runners/index.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/runners/register_repayment.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/runners/register_term_start.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/scenarios/index.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/scenarios/unsuccessful_register_term_start.ts
  test/ts/integration/examples/simple_interest_terms_contract/runners/simple_interest_terms_contract.ts
  test/ts/integration/examples/simple_interest_terms_contract/scenarios/index.ts
  test/ts/integration/examples/simple_interest_terms_contract/scenarios/unsuccessful_register_term_start.ts
  test/ts/integration/examples/simple_interest_terms_contract/simple_interest_terms_contract.ts
  test/ts/integration/repayment_router.ts
  test/ts/integration/token_registry.ts
  test/ts/migrations/2_deploy_dharma_contracts_test.ts
  test/ts/migrations/6_transfer_ownership_to_multisig.ts
  test/ts/test_utils/format.ts
  test/ts/test_utils/multisig.ts
  test/ts/test_utils/utils.ts
  test/ts/unit/collateralizer/collateralizer.ts
  test/ts/unit/collateralizer/runners/index.ts
  test/ts/unit/collateralizer/runners/return_collateral.ts
  test/ts/unit/collateralizer/runners/seize_collateral.ts
  test/ts/unit/collateralizer/scenarios/successful_return.ts
  test/ts/unit/collateralizer/scenarios/successful_seizure.ts
  test/ts/unit/collateralizer/scenarios/unsuccessful_return.ts
  test/ts/unit/collateralizer/scenarios/unsuccessful_seizure.ts
  test/ts/unit/debt_kernel.ts
  test/ts/unit/debt_registry.ts
  test/ts/unit/token_transfer_proxy.ts
  truffle.js
  utils/web3_utils.ts
Labels: needs-review

#104 Feature: Add conditional timelocking to multisig wallet
  contracts/test/mocks/MockDebtToken.sol
  contracts/wallet/DharmaMultiSigWallet.sol
  contracts/wallet/MultiSigWallet.sol
  migrations/2_deploy_dharma_contracts.js
  migrations/6_transfer_ownership_to_multisig.js
  migrations/migration_constants.js
  test/ts/integration/debt_kernel.ts
  test/ts/integration/dharma_multisig_wallet.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/collateralized_simple_interest_terms_contract.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/runners/collateralized_simple_interest_terms_contract.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/runners/index.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/runners/register_repayment.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/runners/register_term_start.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/scenarios/index.ts
  test/ts/integration/examples/collateralized_simple_interest_terms_contract/scenarios/unsuccessful_register_term_start.ts
  test/ts/integration/examples/simple_interest_terms_contract/runners/simple_interest_terms_contract.ts
  test/ts/integration/examples/simple_interest_terms_contract/scenarios/index.ts
  test/ts/integration/examples/simple_interest_terms_contract/scenarios/unsuccessful_register_term_start.ts
  test/ts/integration/examples/simple_interest_terms_contract/simple_interest_terms_contract.ts
  test/ts/integration/repayment_router.ts
  test/ts/integration/token_registry.ts
  test/ts/migrations/2_deploy_dharma_contracts_test.ts
  test/ts/migrations/6_transfer_ownership_to_multisig.ts
  test/ts/test_utils/format.ts
  test/ts/test_utils/multisig.ts
  test/ts/test_utils/utils.ts
  test/ts/unit/collateralizer/collateralizer.ts
  test/ts/unit/collateralizer/runners/index.ts
  test/ts/unit/collateralizer/runners/return_collateral.ts
  test/ts/unit/collateralizer/runners/seize_collateral.ts
  test/ts/unit/collateralizer/scenarios/successful_return.ts
  test/ts/unit/collateralizer/scenarios/successful_seizure.ts
  test/ts/unit/collateralizer/scenarios/unsuccessful_return.ts
  test/ts/unit/collateralizer/scenarios/unsuccessful_seizure.ts
  test/ts/unit/debt_kernel.ts
  test/ts/unit/debt_registry.ts
  test/ts/unit/token_transfer_proxy.ts
  truffle.js
  utils/web3_utils.ts
Labels: needs-review
